import type { Metadata } from 'next'
import './globals.css'
import NavBar from '@/src/components/NavBar'
import { ApiRoutesProvider } from '@/src/contexts/ApiContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body>
        <ApiRoutesProvider>
          <NavBar />
          {children}
        </ApiRoutesProvider>
      </body>
    </html>
  )
}

export default RootLayout
